name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Visit.API/Dockerfile --tag visit-api:latest

    - name: Run docker-compose
      run: docker compose -f ${{ secrets.DOCKER_COMPOSE_FILE_PATH }} up -d
